NHSDigital/eligibility-signposting-api

.gitignore, .tool-versions, README.md, scripts/config/pre-commit.yaml
The template repository is set up expecting asdf to be used as the general tool version manager. One element of the repository which relies on asdf are some of the make commands in scripts/init.mk, one of which is make pre-commit. 
I've made the following changes:
1. Added the pre-requisite for asdf back into the README
2. Added poetry + act to the asdf .tool-versions file, to allow easy install via asdf
3. Added additional pre-commit hooks to the pre-commit config to cover off ruff and pyright.
Some developers want to use pre-commit as it automates running linting etc. (myself included)
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable …
=> Set up repo to allow use of pre-commit (via existing make)

pyproject.toml, src/eligibility_signposting_api/app.py, src/eligibility_signposting_api/config.py, src/eligibility_signposting_api/error_handler.py, src/eligibility_signposting_api/model/eligibility.py, src/eligibility_signposting_api/views/eligibility.py, tests/integration/in_process/test_eligibility_endpoint.py, tests/integration/in_process/test_hello_world_endpoint.py, tests/integration/lambda/test_app_running_as_lambda.py, tests/unit/views/test_eligibility.py, tests/unit/views/test_hello.py
=> ELI-132 Empty endpoint for eligibility

.github/workflows/stage-2-test.yaml, .github/workflows/stage-4-acceptance.yaml, README.md, pyproject.toml, scripts/config/sonar-scanner.properties, scripts/config/vale/styles/config/vocabularies/words/accept.txt, scripts/tests/lint.sh, scripts/tests/unit.sh, src/eligibility_signposting_api/app.py, src/eligibility_signposting_api/config.py, tests/docker-compose.yml, tests/integration/conftest.py
=> eli-137-kt-base-logging-setup

README.md, poetry.lock, pyproject.toml, src/eligibility_signposting_api/app.py, src/eligibility_signposting_api/config.py, src/eligibility_signposting_api/repos/__init__.py, src/eligibility_signposting_api/repos/person_repo.py, src/eligibility_signposting_api/services/__init__.py, src/eligibility_signposting_api/services/person_services.py, src/eligibility_signposting_api/views/__init__.py, src/eligibility_signposting_api/views/eligibility.py, src/eligibility_signposting_api/views/hello.py, tests/integration/conftest.py, tests/unit/services/test_name_services.py, tests/unit/views/test_hello.py
=> Major version bump for Wireup to 1.0

.github/workflows/stage-4-acceptance.yaml, scripts/tests/integration.sh, tests/integration/conftest.py
This PR introduces improvements to the CI workflow and test infrastructure by adding integration test result collection, reporting, and improved test command parameters.
Specifically:
- Integration test results are now uploaded as artifacts during the GitHub Actions workflow.
- Summaries of test results are gathered and reported using `phoenix-actions/test-reporting`.
- Integration test execution has been updated to output JUnit XML for CI consumption.
- The retry logic in `conftest.py` has been enhanced with custom retry attempts and timeout parameters for better test stability.
These changes aim to improve test result visibility in CI and make integration tests more robust and maintainable. With test artifacts and reports now being part of the workflow, it becomes easier to debug …
=> adding Integration Test Results to the pipeline summary

.github/workflows/stage-3-build.yaml, poetry.lock, pyproject.toml, scripts/dependencies.sh, src/eligibility_signposting_api/error_handler.py, src/eligibility_signposting_api/views/eligibility.py, src/eligibility_signposting_api/views/response_models.py, tests/integration/lambda/test_app_running_as_lambda.py, tests/unit/views/test_eligibility.py
See https://hl7.org/fhir/operationoutcome.html and https://pypi.org/project/fhir.resources/
---
=> ELI-136: Use FHIR OperationOutcome for problem reporting.

src/eligibility_signposting_api/model/eligibility.py, src/eligibility_signposting_api/model/rules.py, src/eligibility_signposting_api/views/response_model/eligibility.py, tests/fixtures/builders/model/rule.py, tests/unit/services/test_eligibility_services.py
Implement filter and suppression functionality in eligibilty rules
---
=> ELI-252 - Implement filter and suppression

tests/unit/services/test_eligibility_services.py
=> Test for mulitple campaigns

README.md, infrastructure/modules/lambda/lambda.tf, src/eligibility_signposting_api/config.py, src/eligibility_signposting_api/repos/__init__.py, src/eligibility_signposting_api/repos/campaign_repo.py, src/eligibility_signposting_api/repos/person_repo.py, src/eligibility_signposting_api/services/calculators/eligibility_calculator.py, src/eligibility_signposting_api/services/eligibility_services.py, tests/fixtures/builders/repos/person.py, tests/integration/conftest.py, tests/integration/repo/test_campaign_repo.py, tests/integration/repo/test_person_repo.py, tests/unit/services/calculators/test_eligibility_calculator.py, tests/unit/services/test_eligibility_services.py, tests/unit/test_config.py
=> Refactor/rename repos & extract calculator.

src/eligibility_signposting_api/model/eligibility.py, src/eligibility_signposting_api/services/calculators/eligibility_calculator.py, src/eligibility_signposting_api/services/calculators/rule_calculator.py
=> Extract RuleCalculator from EligibilityCalculator.

src/eligibility_signposting_api/model/eligibility.py, src/eligibility_signposting_api/services/calculators/eligibility_calculator.py, tests/unit/services/calculators/test_eligibility_calculator.py
=> Group campaigns for easy processing

infrastructure/modules/lambda/lambda.tf, infrastructure/modules/s3/kms.tf, infrastructure/stacks/_shared/default_variables.tf, infrastructure/stacks/_shared/locals.tf, infrastructure/stacks/api-layer/iam_roles.tf, infrastructure/stacks/api-layer/lambda.tf
This code contains setting dynamic names to the roles and keys which are part of api-layer. 
✅1. Mulitple workspaces can be created in the stack api-layer
✅2. Only default is allowed in  the stacks such as networking,  iam-developer roles
---
=> terraform code cleanup 

src/eligibility_signposting_api/model/rules.py, src/eligibility_signposting_api/services/calculators/rule_calculator.py, tests/fixtures/builders/model/rule.py, tests/fixtures/builders/repos/person.py, tests/unit/services/calculators/test_eligibility_calculator.py
=> Already vaccinated scenarios covered

src/eligibility_signposting_api/services/calculators/eligibility_calculator.py, tests/unit/services/calculators/test_eligibility_calculator.py
=> Introducing magic cohort in iteration cohorts

src/eligibility_signposting_api/model/rules.py, src/eligibility_signposting_api/services/calculators/eligibility_calculator.py, tests/fixtures/builders/model/rule.py, tests/unit/model/test_rules.py, tests/unit/services/calculators/test_eligibility_calculator.py
=> ELI-150 - Some campaign config validation

src/eligibility_signposting_api/services/calculators/rule_calculator.py, src/eligibility_signposting_api/services/rules/operators.py, tests/unit/services/calculators/test_eligibility_calculator.py, tests/unit/services/operators/test_operators.py
=> Eli 268 impl cohort attribute level

src/eligibility_signposting_api/services/calculators/eligibility_calculator.py, tests/fixtures/builders/model/rule.py, tests/unit/services/calculators/test_eligibility_calculator.py, tests/unit/services/calculators/test_rule_calculator.py
=> Introduced COHORT_LABEL field in iteration rules

infrastructure/modules/lambda/kms.tf, infrastructure/stacks/iams-developer-roles/github_actions_policies.tf
Adding additional permissions for Github account to be able to deploy the stack, and fixing KMS key permissions for Cloudwatch + Lambda
Needed to allow deployment of our stack
---
=> eli-238 - bugfix - fixing github and cloudwatch permissions

src/eligibility_signposting_api/model/rules.py, tests/unit/services/calculators/test_eligibility_calculator.py
=> "O" iteration type in iterations

.github/workflows/cicd-2-publish.yaml, .github/workflows/cicd-3-deploy.yaml, .github/workflows/cicd-4-test.yaml, infrastructure/stacks/iams-developer-roles/github_actions_policies.tf, infrastructure/stacks/iams-developer-roles/github_actions_role.tf, infrastructure/stacks/iams-developer-roles/terraform_developer_role.tf
=> Fix/fire hose GitHub role

.github/workflows/cicd-2-publish.yaml, .github/workflows/cicd-3-deploy.yaml, .github/workflows/cicd-4-test.yaml
=> revert github workflow changes

infrastructure/stacks/api-layer/cloudwatch_alarms.tf, infrastructure/stacks/api-layer/iam_policies.tf, infrastructure/stacks/iams-developer-roles/github_actions_policies.tf, scripts/config/gitleaks.toml
eli-285 and eli-349 adding cloudwatch alarms for a) security and b) ps - API Gateway and Lambda execution
Adding alarms and an associated SNS topic for alarms to be pushed to. The eventual aim is to then use EventBridge to push the records to Splunk via the HEC Http Endpoint.
Aim is to surface alerts related to live service to ITOC. Rather than push *all* logs, we can take a data minimisation approach and only push information which is actionable by ITOC.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and …
=> eli-285 and eli-349 adding cloudwatch alarms

infrastructure/stacks/api-layer/s3_buckets.tf, infrastructure/stacks/iams-developer-roles/github_actions_policies.tf
Adding account level s3 public block
We block public access to s3 buckets we create. Adding in account level protections also means malicious actors / inadvertent s3 creation is protected by default from being made public.
---
=> eli-386 blocking s3 public access at account level

infrastructure/stacks/api-layer/patient_check.tf
=> ELI-397: AWS api gateway to handle bad request param error

infrastructure/stacks/api-layer/eventbridge.tf
Using JSON Encode in eventbridge, where the 'raw' record is being used in Splunk leads to AWS substituting '<' and '>' characters with their unicode string equivalents. This then resulted in the values not being substituted for the actual ones. The change here is to use heredoc string format for the input template.
This looks to be a bug in the way Terraform and AWS interact e.g. https://github.com/hashicorp/terraform-provider-aws/issues/21959
We need the proper log messages to be sent
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data …
=> eli-304 - bugfix - amending eventbridge template

infrastructure/stacks/api-layer/locals.tf
**Based off v1.0.0-rc.2**
Our Prod subdomain has to be prod.eligibility-signposting-api.**national**.nhs.uk and not just prod.eligibility-signposting-api.nhs.uk
We need to make sure our API Gateway is set up for the different domain naming pattern.
---
=> eli-470 updating prod subdomain to include national.nhs.uk

infrastructure/stacks/iams-developer-roles/github_actions_policies.tf, infrastructure/stacks/iams-developer-roles/iams_permissions_boundary.tf
Adding permissions for dynamoDB:UpdateTable to Github OIDC role
We recently added changes to dynamoDB encryption, which failed on deployment as the Github role did not have permissions to update existing tables. Adding these permissions
---
=> bugfix - adding dynamoDB UpdateTable permissions to the Github OID role, to unblock dev deployments

.github/workflows/base-deploy.yml, .github/workflows/cicd-2-publish.yaml, .github/workflows/cicd-3-test-deploy.yaml, infrastructure/stacks/api-layer/s3_buckets.tf, infrastructure/stacks/iams-developer-roles/github_actions_policies.tf
=> adding back the reuse artifacts code with fix
