NHSDigital/eligibility-signposting-api

scripts/dependencies.sh
=> [ELI-19] Ensure poetry-plugin-lambda-build is installed.

.github/workflows/stage-2-test.yaml, pyproject.toml, scripts/config/sonar-scanner.properties, scripts/tests/unit.sh
=> ELI-117 - SonarQube test coverage reporting.

poetry.lock, pyproject.toml, src/eligibility_signposting_api/config.py
=> structured logging

src/eligibility_signposting_api/services/eligibility_services.py, tests/integration/conftest.py, tests/integration/repo/test_eligibility_repo.py, tests/unit/services/test_eligibility_services.py
=> ELI-210: Review feedback

src/eligibility_signposting_api/services/rules/operators.py
=> Deduplicate Operator classes.

README.md, src/eligibility_signposting_api/model/eligibility.py, src/eligibility_signposting_api/services/eligibility_services.py, src/eligibility_signposting_api/views/eligibility.py, src/eligibility_signposting_api/views/response_models.py, tests/integration/in_process/test_eligibility_endpoint.py, tests/integration/lambda/test_app_running_as_lambda.py, tests/unit/services/test_eligibility_services.py, tests/unit/views/test_eligibility.py, tests/utils/builders.py, tests/utils/matchers/eligibility.py
=> Use John's response schema rather than FHIR.

src/eligibility_signposting_api/services/eligibility_services.py, src/eligibility_signposting_api/services/rules/operators.py, tests/unit/services/operators/test_operators.py
=> updated comparison operator

src/eligibility_signposting_api/model/eligibility.py, src/eligibility_signposting_api/model/rules.py, src/eligibility_signposting_api/services/eligibility_services.py, src/eligibility_signposting_api/views/eligibility.py, tests/integration/conftest.py
=> ELI-211 Return basic reason details.

src/eligibility_signposting_api/services/eligibility_services.py, src/eligibility_signposting_api/services/rules/operators.py, tests/integration/conftest.py, tests/integration/in_process/test_eligibility_endpoint.py, tests/unit/services/operators/test_operators.py
=> ELI-211 - Add integration tests for simple exclusion rule.

README.md, src/eligibility_signposting_api/config.py, src/eligibility_signposting_api/model/rules.py, src/eligibility_signposting_api/repos/eligibility_repo.py, src/eligibility_signposting_api/repos/rules_repo.py, tests/integration/conftest.py, tests/integration/repo/test_rules_repo.py
=> ELI-207 - Make DynamoDB table name configurable.

src/eligibility_signposting_api/services/rules/operators.py, tests/integration/in_process/test_eligibility_endpoint.py, tests/unit/services/operators/test_operators.py
=> Test & behaviours match for now - checking with John.

infrastructure/stacks/_shared/default_variables.tf, infrastructure/stacks/_shared/locals.tf, infrastructure/stacks/api-layer/iam_policies.tf, infrastructure/stacks/api-layer/iam_roles.tf, infrastructure/stacks/iams-developer-roles/github_actions_policies.tf, infrastructure/stacks/iams-developer-roles/github_actions_role.tf, infrastructure/stacks/iams-developer-roles/iams_permissions_boundary.tf, infrastructure/stacks/iams-developer-roles/outputs.tf, infrastructure/stacks/iams-developer-roles/terraform_developer_policies.tf, infrastructure/stacks/iams-developer-roles/terraform_developer_role.tf
=> default workspace is the owner of iam policies and roles

infrastructure/Makefile, infrastructure/modules/dynamodb/kms.tf
=> kms alias made thread safe, cleaned make file

src/eligibility_signposting_api/services/rules/operators.py, tests/unit/services/operators/test_operators.py
=> ELI-236 - Add NVL Default to Operators

src/eligibility_signposting_api/services/rules/operators.py, tests/unit/services/operators/test_operators.py
=> ELI-237 Offset date operators

README.md
=> Add context diagram to README

pyproject.toml, src/eligibility_signposting_api/model/eligibility.py, src/eligibility_signposting_api/model/rules.py, src/eligibility_signposting_api/services/eligibility_services.py, tests/fixtures/builders/model/eligibility.py, tests/fixtures/builders/model/rule.py, tests/fixtures/builders/repos/eligibility.py, tests/integration/conftest.py, tests/integration/in_process/test_eligibility_endpoint.py, tests/integration/lambda/test_app_running_as_lambda.py, tests/integration/repo/test_eligibility_repo.py, tests/unit/services/test_eligibility_services.py
=> ELI-151 - Cohort based filtering

src/eligibility_signposting_api/services/calculators/eligibility_calculator.py
=> eligibility calculator code refactor

.tool-versions
=> pinning version to latest for grype

tests/unit/services/calculators/test_eligibility_calculator.py
=> ELI-253 Added test for missing vaccine row.

.github/workflows/cicd-1-pull-request.yaml, .github/workflows/cicd-3-deploy.yaml
adding in version bump selection to control major minor and patch increments
changing pull request workflow trigger to only commits to a non draft pr
- [x ] Refactoring (non-breaking change)
- [ x] New feature (non-breaking change which adds functionality)
- [ x] I am familiar with the [contributing guidelines](../docs/CONTRIBUTING.md)
- [ x] I have followed the code style of the project
- [x ] I have updated the documentation accordingly
- [ x] This PR is a result of pair or mob programming
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive …
=> adding in improvements from meeting

infrastructure/stacks/iams-developer-roles/github_actions_policies.tf
The github role needs to amend KMS and IAM policies, so we need to add additional permissions for the role
Deployment will fail without these
- [] I have added tests to cover my changes
---
=> eli-131 adding additional permissions for github role

src/eligibility_signposting_api/views/eligibility.py
=> fix if conditions in response builder

tests/e2e/data/dynamoDB/AUTO_RSV_SB_001.json, tests/e2e/data/dynamoDB/AUTO_RSV_SB_002.json, tests/e2e/data/dynamoDB/AUTO_RSV_SB_003.json, tests/e2e/data/dynamoDB/AUTO_RSV_SB_004.json, tests/e2e/data/dynamoDB/AUTO_RSV_SB_005.json, tests/e2e/data/dynamoDB/AUTO_RSV_SB_006.json, tests/e2e/data/dynamoDB/AUTO_RSV_SB_007.json, tests/e2e/data/dynamoDB/AUTO_RSV_SB_008.json, tests/e2e/data/dynamoDB/AUTO_RSV_SB_009.json, tests/e2e/data/dynamoDB/AUTO_RSV_SB_010.json, tests/e2e/data/dynamoDB/AUTO_RSV_SB_011.json, tests/e2e/data/dynamoDB/AUTO_RSV_SB_012.json, tests/e2e/data/dynamoDB/AUTO_RSV_SB_013.json, tests/e2e/data/dynamoDB/AUTO_RSV_SB_014.json, tests/e2e/data/responses/AUTO_RSV_SB_001.json, tests/e2e/data/responses/AUTO_RSV_SB_002.json, tests/e2e/data/responses/AUTO_RSV_SB_003.json, tests/e2e/data/responses/AUTO_RSV_SB_004.json, tests/e2e/data/responses/AUTO_RSV_SB_005.json, tests/e2e/data/responses/AUTO_RSV_SB_006.json, tests/e2e/data/responses/AUTO_RSV_SB_007.json, tests/e2e/data/responses/AUTO_RSV_SB_008.json, tests/e2e/data/responses/AUTO_RSV_SB_009.json, tests/e2e/data/responses/AUTO_RSV_SB_010.json, tests/e2e/data/responses/AUTO_RSV_SB_011.json, tests/e2e/data/responses/AUTO_RSV_SB_012.json, tests/e2e/data/responses/AUTO_RSV_SB_013.json, tests/e2e/data/responses/AUTO_RSV_SB_014.json
=> + feature/adw-new-test-data-for-e2e-fix

src/eligibility_signposting_api/repos/person_repo.py, tests/fixtures/builders/repos/person.py, tests/integration/repo/test_person_repo.py
=> removed "PERSON" prefix req in nhs number

infrastructure/modules/lambda/lambda.tf, infrastructure/modules/lambda/variables.tf, infrastructure/stacks/api-layer/lambda.tf
=> log level set to INFO

src/eligibility_signposting_api/views/eligibility.py
=> log nhs number

.github/workflows/manual-terraform-apply.yaml
=> updated manual-terraform apply

infrastructure/modules/kinesis_firehose/kms.tf, infrastructure/modules/kinesis_firehose/variables.tf, infrastructure/stacks/api-layer/kinesis_firehose.tf
=> fix - kms firehose permissions

infrastructure/modules/api_gateway/cloudwatch.tf, src/eligibility_signposting_api/services/eligibility_services.py, tests/integration/lambda/test_app_running_as_lambda.py
=> ELI-331: Mask PII/GDPR info

tests/fixtures/builders/model/eligibility.py, tests/fixtures/builders/model/rule.py
=> Provided appropriate values to factory methods in tests

infrastructure/stacks/api-layer/s3_buckets.tf, infrastructure/stacks/iams-developer-roles/github_actions_policies.tf
Reverts NHSDigital/eligibility-signposting-api#278
=> Revert "eli-386 blocking s3 public access at account level"

infrastructure/modules/s3/s3.tf
Server access logging was enabled on the S3 buckets reviewed, however write permissions were not assigned to the log deliverer. This would prevent logs from being written to the S3 bucket, potentially impacting any post-incident forensic activities.
Write permissions were not available to the log deliverer on any of the access log buckets.
We want audit records to be logged
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive …
=> eli-388 adding access log permissions for audit buckets

src/eligibility_signposting_api/services/calculators/eligibility_calculator.py, tests/unit/services/calculators/test_eligibility_calculator.py
=> ELI-399: Fixing Future Iteration.StartDate Resulting in 500 Error

src/eligibility_signposting_api/model/campaign_config.py, src/rules_validation_api/validators/campaign_config_validator.py, tests/integration/conftest.py, tests/integration/lambda/test_app_running_as_lambda.py, tests/unit/model/test_campaign_config.py
=> ELI-399: Fixing start date validation

src/eligibility_signposting_api/model/eligibility_status.py, src/eligibility_signposting_api/services/calculators/eligibility_calculator.py, src/eligibility_signposting_api/views/eligibility.py, tests/fixtures/builders/model/eligibility.py, tests/unit/services/calculators/test_eligibility_calculator.py
=> Bugfix to change response grouping from name to priority

src/eligibility_signposting_api/repos/person_repo.py, tests/integration/conftest.py, tests/integration/repo/test_person_repo.py
=> ELI-406: no person_data, so error response

.github/workflows/cicd-2-publish.yaml
=> (ELI-444) fixing path mistake

src/eligibility_signposting_api/services/processors/action_rule_handler.py, src/eligibility_signposting_api/services/processors/token_processor.py
=> ELI-441: Fix Sonar code smells

.github/workflows/base-deploy.yml
=> (ELI-452) changed ordering

infrastructure/stacks/api-layer/assumed_role_permissions_boundary.tf
=> [ELI-422] Added S3 tagging operations to permissions boundary

infrastructure/stacks/api-layer/iam_policies.tf
=> Added new kms policy for external write role

.github/workflows/regression-tests.yml, scripts/run_regression_tests.py
This removes the pr_label from the regression tests script
and removes "product" from the workflow
This will allow the regression tests step to run unblocking the builds
---
=> removal of "product" and "pr label"

.github/workflows/base-deploy.yml, .github/workflows/cicd-2-publish.yaml, .github/workflows/cicd-3-test-deploy.yaml, infrastructure/stacks/api-layer/s3_buckets.tf, infrastructure/stacks/iams-developer-roles/github_actions_policies.tf
=> ELi-442 bring back the old deployment style to unlock test deployments

.github/workflows/cicd-2-publish.yaml, .github/workflows/cicd-3-test-deploy.yaml
=> ELI-446: Adds validate toggle step explicitly for dev and test

.github/workflows/cicd-2-publish.yaml, .github/workflows/cicd-3-test-deploy.yaml
=> ELI-446: Adds env name explicitly for validating feature toggle

infrastructure/modules/api_gateway/cloudwatch.tf, infrastructure/modules/kinesis_firehose/outputs.tf, infrastructure/stacks/api-layer/cloudwatch.tf, infrastructure/stacks/api-layer/truststore_s3_bucket.tf
=> infra: add kms policy dependency for firehouse cloudwatch logs
